const GAME_BOARD_DIM = 10;
const FIRST_PLAYER = 1;
const SECOND_PLAYER = -1;
const GAME_FPS = 1000 / 60;
const MIN_TERMINAL_WIDTH = 80;
const MIN_TERMINAL_HEIGHT = 24;


export { GAME_BOARD_DIM, FIRST_PLAYER, SECOND_PLAYER, GAME_FPS, MIN_TERMINAL_HEIGHT, MIN_TERMINAL_WIDTH };